
wifi:
    ssid: !secret wifi_ssid2
    password: !secret wifi_password2

# Enable Home Assistant API
api:
    id: api_server
    encryption:
      key: !secret api_key
  
ota:
    platform: esphome
    password: !secret ota_password

time:
    - platform: homeassistant
      id: time_homeassistant
      on_time_sync:
        - component.update: sensor_uptime_timestamp
    
sensor:
    - platform: uptime
      id: sensor_uptime
    
    - platform: template
      id: sensor_uptime_timestamp
      name: "${friendly_name} Uptime"
      device_class: "timestamp"
      accuracy_decimals: 0
      update_interval: never
      lambda: |-
        static float timestamp = (id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state);
        return timestamp;
    
    - platform: wifi_signal
      name: ${friendly_name} Signal
      update_interval: 60s

switch:
    - platform: restart
      name: "${friendly_name} Restart"