# Detecting chip type... ESP32
# Chip is ESP32-D0WD-V3 (revision v3.1)
# Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
# Crystal is 40MHz
# MAC: 08:d1:f9:c7:14:b0
# Uploading stub...
# Running stub...
# Stub running...
# Manufacturer: 5e
# Device: 4016
# Detected flash size: 4MB


substitutions:
    name: reflow-controller
    device_description: Reflow Controller
    friendly_name: Reflow Controller
  
packages:
    common: !include 
        file: ../common_no_web.yaml
        vars: 
            friendly_name: ${friendly_name}
  
esphome:
    name: ${name}
    comment: ${device_description}
  
esp32:
    board: esp32dev
    framework:
      type: esp-idf
  
# Enable logging
logger:
    level: DEBUG

external_components:
  - source: components

light:
  - platform: status_led
    name: "${friendly_name} Led"
    pin: 
        number: GPIO12
        ignore_strapping_warning: true

switch:
  - platform: gpio
    id: reflow_switch
    pin: GPIO04
    name: "${friendly_name} Switch"

spi:
  miso_pin: GPIO19
  clk_pin: GPIO18

sensor:
  - platform: max6675
    id: temperature_sensor
    name: "Temperature sensor"
    cs_pin: 
      number: GPIO05
      ignore_strapping_warning: true
    update_interval: 1s

reflow_curve:
  id: reflow_curve_component
  reflow_switch: reflow_switch
  temperature_sensor: temperature_sensor

reflow_web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  reflow_curve: reflow_curve_component
  update_interval: 1s

