# Detecting chip type... ESP32-C3
# Chip is ESP32-C3 (revision v0.4)
# Features: WiFi, BLE
# Crystal is 40MHz
# MAC: ec:da:3b:a4:c9:cc
# Uploading stub...
# Running stub...
# Stub running...
# Manufacturer: 5e
# Device: 4016
# Detected flash size: 4MB


substitutions:
    name: nibe-controller-c3
    device_description: Nibe Controller C3
    friendly_name: Nibe Controller C3
  
packages:
    common: !include 
        file: ../common.yaml
        vars: 
            friendly_name: ${friendly_name}
  
esphome:
    name: ${name}
    comment: ${device_description}
    platformio_options:
      board_build.flash_mode: dio
  
esp32:
    board: esp32-c3-devkitm-1
    variant: esp32c3 
    framework:
      type: esp-idf
    
  
# Enable logging
logger:
 #   baud_rate: 9600
    level: DEBUG

light:
  - platform: status_led
    name: "${friendly_name} Led"
    pin: 
        number: GPIO19

switch:
  - platform: gpio
    id: output1
    pin: GPIO06
    name: "${friendly_name} Output 1"
  - platform: gpio
    id: output2
    pin: GPIO07
    name: "${friendly_name} Output 2"

binary_sensor:
  - platform: gpio
    id: input1
    name: "${friendly_name} Input 1"
    pin: 
        number: GPIO04
  - platform: gpio
    id: input12
    name: "${friendly_name} Input 2"
    pin: 
        number: GPIO05
    
    

