# Detecting chip type... ESP32-C6
# Chip is ESP32-C6 (QFN40) (revision v0.0)
# Features: WiFi 6, BT 5, IEEE802.15.4
# Crystal is 40MHz
# MAC: 40:4c:ca:ff:fe:42:36:1c
# BASE MAC: 40:4c:ca:42:36:1c
# MAC_EXT: ff:fe
# Uploading stub...
# Running stub...
# Stub running...
# Manufacturer: c8
# Device: 4016
# Detected flash size: 4MB


substitutions:
    name: nibe-controller-c6
    device_description: Nibe Controller C6
    friendly_name: Nibe Controller C6
  
packages:
    common: !include 
        file: ../common.yaml
        vars: 
            friendly_name: ${friendly_name}
  
esphome:
    name: ${name}
    comment: ${device_description}
  
esp32:
    board: esp32-c6-devkitc-1
    variant: esp32c6
    framework:
      type: esp-idf
#      version: "5.3.1"
#      platform_version: 6.9.0
  
# Enable logging
logger:
    level: DEBUG

light:
  - platform: status_led
    name: "${friendly_name} Led"
    pin: 
        number: GPIO13

switch:
  - platform: gpio
    id: output11
    pin: GPIO19
    name: "${friendly_name} Output 11"
  - platform: gpio
    id: output12
    pin: GPIO18
    name: "${friendly_name} Output 12"
  - platform: gpio
    id: output13
    pin: GPIO20
    name: "${friendly_name} Output 13"
  - platform: gpio
    id: output14
    pin: GPIO21
    name: "${friendly_name} Output 14"

binary_sensor:
  - platform: gpio
    id: input11
    name: "${friendly_name} Input 11"
    pin: 
        number: GPIO04
  - platform: gpio
    id: input12
    name: "${friendly_name} Input 12"
    pin: 
        number: GPIO05
    
    

